# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - secv1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and activate virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          # Clean up temporary files to avoid disk space issues
          rm -rf /tmp/*
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      # Optional: Add step to run tests here (e.g., pytest)

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "venv/*" ".git*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_52E9D9BA326A4732822CEED46BD2C29A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0EFCDF8417F64FFFA57F8429C5EF4374 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_23BEC7EC9C8249E2A2A842B2C9327028 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'secv1'
          slot-name: 'Production'
